import Navbar from "./components/Navbar";
import "./styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-50 ">
        <header className="container mx-auto">
          <Navbar />
        </header>

        {children}
      </body>
    </html>
  );
}
